from __future__ import annotations

import hashlib
import json
from pathlib import Path
from runpy import run_path

import pytest

TOOL = run_path(str(Path(__file__).resolve().parents[1] / "tools" / "update_runtime_lock.py"))
RuntimeLockGenerationError = TOOL["RuntimeLockGenerationError"]
build_runtime_lock = TOOL["build_runtime_lock"]
check_runtime_lock = TOOL["check_runtime_lock"]
parse_hashed_requirements = TOOL["parse_hashed_requirements"]
write_runtime_lock = TOOL["write_runtime_lock"]

_HASH_A = "a" * 64
_HASH_B = "b" * 64


def test_parse_hashed_requirements_flattens_continuations_and_ignores_comments() -> None:
    source = (
        "# generated by uv\n\n"
        f"zeta==2.0 \\\n    --hash=sha256:{_HASH_A} \\\n    --hash=sha256:{_HASH_B}\n"
        "# via alpha\n"
        f"alpha==1.0 --hash=sha256:{_HASH_B}\n"
    )

    assert parse_hashed_requirements(source, source_name="fixture.txt") == (
        f"zeta==2.0 --hash=sha256:{_HASH_A} --hash=sha256:{_HASH_B}",
        f"alpha==1.0 --hash=sha256:{_HASH_B}",
    )


@pytest.mark.parametrize(
    "source",
    [
        "package>=1.0 --hash=sha256:" + _HASH_A + "\n",
        "package==1.0\n",
        "-e git+https://example.invalid/package.git\n",
        "package==1.0 --hash=sha256:bad\n",
        "package==1.0 \\\n",
        "package==1.0 --hash=sha256:" + _HASH_A + "\nPackage==1.0 --hash=sha256:" + _HASH_B + "\n",
    ],
)
def test_parse_hashed_requirements_rejects_unpinned_or_ambiguous_entries(source: str) -> None:
    with pytest.raises(RuntimeLockGenerationError):
        parse_hashed_requirements(source, source_name="fixture.txt")


_WHEEL_NAME = "mlx_audio-0.4.8+speechrail.1-py3-none-any.whl"


def _write_inputs(root: Path) -> tuple[Path, Path]:
    runtime = root / "src" / "speechrail" / "assets" / "runtime"
    runtime.mkdir(parents=True)
    asr = runtime / "asr.txt"
    tts = runtime / "tts.txt"
    asr.write_text(f"alpha==1.0 --hash=sha256:{_HASH_A}\n", encoding="utf-8")
    tts.write_text(f"zeta==2.0 --hash=sha256:{_HASH_B}\n", encoding="utf-8")
    return asr, tts


def _write_engine_build(root: Path, *, wheel_bytes: bytes = b"engine-wheel") -> Path:
    dist = root / "vendor" / "engine-build" / "dist"
    dist.mkdir(parents=True)
    wheel = dist / _WHEEL_NAME
    wheel.write_bytes(wheel_bytes)
    provenance = {
        "filename": _WHEEL_NAME,
        "sha256": hashlib.sha256(wheel_bytes).hexdigest(),
        "source_repository": "https://github.com/Blaizzy/mlx-audio",
        "source_revision": "b" * 40,
        "patch_sha256": "c" * 64,
        "build_inputs_sha256": "d" * 64,
    }
    (dist / "provenance.json").write_text(json.dumps(provenance), encoding="utf-8")
    return dist / "provenance.json"


def test_build_runtime_lock_hashes_exact_requirement_files_and_uses_requested_python(
    tmp_path: Path,
) -> None:
    asr_path, tts_path = _write_inputs(tmp_path)

    payload = build_runtime_lock(tmp_path, lock_id="candidate-314", python_version="3.14.7")

    assert payload == {
        "id": "candidate-314",
        "python": "3.14.7",
        "asr_requirements": [f"alpha==1.0 --hash=sha256:{_HASH_A}"],
        "tts_requirements": [f"zeta==2.0 --hash=sha256:{_HASH_B}"],
        "ffmpeg_artifact": "imageio-ffmpeg==0.6.0",
        "file_hashes": {
            "runtime/asr.txt": hashlib.sha256(asr_path.read_bytes()).hexdigest(),
            "runtime/tts.txt": hashlib.sha256(tts_path.read_bytes()).hexdigest(),
        },
    }


def test_build_runtime_lock_records_the_built_engine_wheel_pin(tmp_path: Path) -> None:
    _write_inputs(tmp_path)
    _write_engine_build(tmp_path)

    payload = build_runtime_lock(tmp_path, lock_id="candidate-314", python_version="3.14.7")

    assert payload["engine_wheel"] == {
        "filename": _WHEEL_NAME,
        "sha256": hashlib.sha256(b"engine-wheel").hexdigest(),
        "source_repository": "https://github.com/Blaizzy/mlx-audio",
        "source_revision": "b" * 40,
        "patch_sha256": "c" * 64,
        "build_inputs_sha256": "d" * 64,
    }


def test_build_runtime_lock_rejects_a_mismatched_engine_wheel(tmp_path: Path) -> None:
    _write_inputs(tmp_path)
    provenance = _write_engine_build(tmp_path)
    payload = json.loads(provenance.read_text(encoding="utf-8"))
    payload["sha256"] = "f" * 64
    provenance.write_text(json.dumps(payload), encoding="utf-8")

    with pytest.raises(RuntimeLockGenerationError, match="engine wheel"):
        build_runtime_lock(tmp_path, lock_id="candidate-314", python_version="3.14.7")


def test_build_runtime_lock_rejects_non_314_python_and_invalid_id(tmp_path: Path) -> None:
    _write_inputs(tmp_path)

    with pytest.raises(RuntimeLockGenerationError, match=r"3\.14"):
        build_runtime_lock(tmp_path, lock_id="candidate", python_version="3.13.15")
    with pytest.raises(RuntimeLockGenerationError, match="id"):
        build_runtime_lock(tmp_path, lock_id="../escape", python_version="3.14.7")


def test_write_runtime_lock_is_atomic_and_check_mode_is_read_only(tmp_path: Path) -> None:
    _write_inputs(tmp_path)
    payload = build_runtime_lock(tmp_path, lock_id="candidate-314", python_version="3.14.7")

    write_runtime_lock(tmp_path, payload)
    lock_path = tmp_path / "src" / "speechrail" / "assets" / "runtime-lock.json"
    original = lock_path.read_bytes()
    original_mtime = lock_path.stat().st_mtime_ns

    assert check_runtime_lock(tmp_path, payload)
    assert lock_path.read_bytes() == original
    assert lock_path.stat().st_mtime_ns == original_mtime

    changed = dict(payload)
    changed["id"] = "different"
    assert not check_runtime_lock(tmp_path, changed)
    assert lock_path.read_bytes() == original
    assert lock_path.stat().st_mtime_ns == original_mtime
    assert not list(lock_path.parent.glob("*.tmp"))
